### ISSUE TITLE
Demande à devenir membre du projet

### ISSUE THREAD

**Issue by eghazal** [projets2017cl/nfp103#12]
![image](https://user-images.githubusercontent.com/22723667/27705377-58b4e7cc-5d16-11e7-8cfd-7fc67d2254c7.png)
![image](https://user-images.githubusercontent.com/22723667/27705394-60eb49a4-5d16-11e7-8a96-6a0bc0d91132.png)

**Comment by pascalfares** [comment]
devenie membre https://github.com/orgs/projets2017cl/teams/nfp103
