### ISSUE TITLE
8403 f / Jad Sayegh / JadSay

### ISSUE THREAD

**Issue by JadSay** [projets2017cl/nfp103#27]

**Comment by pascalfares** [comment]
Tu avais déjà un autre utilisateur JadSayegh?

https://github.com/orgs/projets2017cl/teams/nfp103/members

**Comment by JadSay** [comment]
JadSayegh avec mon email personnel.
JadSay avec mon email isae.

2017-07-01 11:12 GMT+03:00 Pascal Fares <notifications@github.com>:
