### ISSUE TITLE
Présentation du projet et premières idée

### ISSUE THREAD

**Issue by pascalfares** [projets2017cl/nfp103#29]
Réfléchir et proposer un sujet de projet

**Comment by pascalfares** [comment]
@nfp103 

Voir le sujet ici https://sites.google.com/a/isae.edu.lb/projet2017/les-projets-2017/nfp103---accov

**Comment by walid-amer** [comment]
voici le lien vers mon projet accov (en progression) : 
https://github.com/walid-amer/projet-accov-2017/tree/accovproject

**Comment by ayounes3333** [comment]
voici le lien vers mon projet accov (en progression)
https://github.com/ayounes3333/nfp103
