### ISSUE TITLE
418 n / Aless Hosry / Aless

### ISSUE THREAD

**Issue by alesshosry** [projets2017cl/nfp103#4]

**Comment by pascalfares** [comment]
Tu n'est pas dans la classroom?

**Comment by alesshosry** [comment]
Bonsoir DR, si je suis dans la classroom
![classroom](https://user-images.githubusercontent.com/26387399/27691144-d95b2dda-5ceb-11e7-860a-be3a61456678.png)
![github](https://user-images.githubusercontent.com/26387399/27691145-d9600f94-5ceb-11e7-8e62-b372433517af.png)
![classroom2](https://user-images.githubusercontent.com/26387399/27691808-d767cc16-5ced-11e7-9c17-b4102938c9e8.png)

**Comment by pascalfares** [comment]
repondre au devoir et faire ce que tu as fait ici ... c'est ok pour cette fois ci... rejoindre l' invitation a la team https://github.com/orgs/projets2017cl/teams/nfp103
