### ISSUE TITLE
Aless Hosry / 418n / Projet accov

### ISSUE THREAD

**Issue by alesshosry** [projets2017cl/nfp103#43]
https://github.com/AlessHo/Accov_Projet_2017

**Comment by alesshosry** [comment]
Bonjour dr @pascalfares ,
J'ai créé mon projet, SACA est le serveur et les autres sont les clients; conection se fait entre les SACA et clients a travers les sockets. Pour chaque genre de client un numero de port specifique est créé. Il me reste encore a cree les commandes des controller pour les envoyer aux avions.

**Comment by pascalfares** [comment]
OK voir https://projets2017cl.github.io/nfp103/

**Comment by AlessHo** [comment]
@pascalfares , pourrai-je vous voir aujourd'hui apres midi? Apres 3 h merci
--

**Comment by alesshosry** [comment]
@pascalfares pourrai-je venir aujourd'hui au cnam? apres midi , apres 3h? Merci
